learning_logs/urls.py
'''определяет схемы URL для learning_logs'''
from django.urls import path
from . import views
app_name = 'learning_logs'
urlpatterns = [
    #home page
    path('',views.index, name='index'),
    #page with list of topics
    path('topics/', views.topics, name='topics'),
    #topic page
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    #page for input user new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    #page to input new entries about topic
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    #page for edit entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

nice_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('', include('learning_logs.urls')),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    #start URL authorization as default
    path('', include('django.contrib.auth.urls')),
    #register page
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    '''topic, that user learn'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        '''retun stringh predstavlenie about model'''
        return self.text

class Entry(models.Model):
    '''info, witch were leanned about the topic'''
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        '''retun stringh idea about model'''
        if len(self.text) > 50:
            return  f'{self.text[:50]}...'
        else:
            return self.text
        

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic
from .models import Entry
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm
def index(request):
    '''homepage app learning_logs'''
    return render(request, 'learning_logs/index.html')

def check_topic_owner(request):
    if topic.owner != request.user:
        raise Http404

@login_required
def topics(request):
    '''shows the list of topics'''
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    '''display one topic and notes about it'''
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    '''determine new topic'''
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    '''add new entry'''
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        #Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    # Вывести пустую или недействительную форму.
    context = {'topic':topic, 'form':form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    '''edit entry and save new'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    '''register new user'''
    if request.method != 'POST':
       form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
 <head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1,
     shrink-to-fit=no">
   <title>Learning Log</title>
   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}
 </head>
 <body>
   <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

     <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
         Learning Log</a>

     <button class="navbar-toggler" type="button" data-toggle="collapse"
         data-target="#navbarCollapse" aria-controls="navbarCollapse"
         aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span></button>
     <div class="collapse navbar-collapse" id="navbarCollapse">
       <ul class="navbar-nav mr-auto">
         <li class="nav-item">
           <a class="nav-link" href="{% url 'learning_logs:topics'%}">Topics</a></li>
       </ul>
       <ul class="navbar-nav ml-auto">
         {% if user.is_authenticated %}
           <li class="nav-item">
             <span class="navbar-text">Hello, {{ user.username }}.</span>
           </li>
           <li class="nav-item">
             <!--<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>-->
             <form action="{% url 'users:logout' %}" method="post">
               {% csrf_token %}
               <button type="submit">Logout</button>
             </form>
           </li>
         {% else %}
           <li class="nav-item">
             <a class="nav-link" href="{% url 'users:register' %}">Register</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
         {% endif %}
       </ul>
     </div>
   </nav>

   <main role="main" class="container">
     <div class="pb-5 mb-2 border-bottom">
       {% block page_header %}{% endblock page_header %}
     </div>
     <div>
       {% block content %}{% endblock content %}
     </div>
   </main>

 </body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
  <h2><p>Edit entry <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p></h2>
{% endblock page_header %}
{% block content %}

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit class=btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html"%}

{% block page_header %}
  <div class='jumbotron'>
    <h1 class="display-3">Track your learning.</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the
      topics you're learning about. Whenever you learn something new
      about a topic, make an entry summarizing what you've learned.</p>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
      role="button">Register &raquo;</a>
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
  <h2><p>Add a new entry about <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p></h2>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name='submit class="btn btn-primary'>Add entry</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% load bootstrap4 %}

{% block page_header %}
  <h2>Add a new topic:</h2>
{% endblock page_header %}

{% block content %}
  <form method='post' action="{% url 'learning_logs:new_topic' %}" class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add topic</button>
    {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
<a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
            edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

  <ul>
      {% for topic in topics %}
        <li><h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3></li>
      {% empty %}
      <li><h3>No topics have been added yet.</h3></li>
      {% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</h3>

{% endblock content %}